// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eovmgiwuviqgggqkdtma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdm1naXd1dmlxZ2dncWtkdG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzY5MDcsImV4cCI6MjA2NzE1MjkwN30.YS-1xLLDjrQd04VCey8psEJT439rdvFput7jMD476sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});